# Generated by Django 4.2.17 on 2024-12-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否在职')),
                ('description', models.TextField(blank=True, verbose_name='工作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.TextField(blank=True, verbose_name='链接描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社交主页',
                'verbose_name_plural': '社交主页',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('level', models.CharField(max_length=50, verbose_name='掌握程度')),
                ('description', models.TextField(blank=True, verbose_name='技能描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '技能特长',
                'verbose_name_plural': '技能特长',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('role', models.CharField(max_length=100, verbose_name='担任角色')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否进行中')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(verbose_name='布局配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_layout', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '档案布局',
                'verbose_name_plural': '档案布局',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='作品标题')),
                ('type', models.CharField(choices=[('design', '设计作品'), ('development', '开发项目'), ('writing', '文章/文档'), ('research', '研究成果'), ('other', '其他')], max_length=20, verbose_name='作品类型')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', verbose_name='封面图')),
                ('description', models.TextField(blank=True, verbose_name='作品描述')),
                ('link', models.URLField(blank=True, verbose_name='作品链接')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='portfolio/attachments/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '作品集',
                'verbose_name_plural': '作品集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='语言名称')),
                ('level', models.CharField(choices=[('native', '母语'), ('fluent', '精通'), ('professional', '熟练'), ('intermediate', '中等'), ('basic', '基础')], max_length=20, verbose_name='掌握程度')),
                ('certificate', models.CharField(blank=True, max_length=100, verbose_name='语言证书')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='考试成绩')),
                ('description', models.TextField(blank=True, verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '语言能力',
                'verbose_name_plural': '语言能力',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='期望职位')),
                ('job_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('internship', '实习'), ('freelance', '自由职业')], default='full_time', max_length=20, verbose_name='工作类型')),
                ('salary_type', models.CharField(choices=[('monthly', '月薪'), ('annual', '年薪'), ('daily', '日薪'), ('hourly', '时薪')], default='monthly', max_length=20, verbose_name='薪资类型')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='最低薪资')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='最高薪资')),
                ('cities', models.JSONField(default=list, verbose_name='期望城市')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='期望行业')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='补充说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_intention', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '求职意向',
                'verbose_name_plural': '求职意向',
                'db_table': 'user_job_intention',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('degree', models.CharField(max_length=50, verbose_name='学历')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否在读')),
                ('description', models.TextField(blank=True, verbose_name='教育经历描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('issuing_authority', models.CharField(max_length=100, verbose_name='发证机构')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('description', models.TextField(blank=True, verbose_name='证书描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '证书奖项',
                'verbose_name_plural': '证书奖项',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地')),
                ('job_title', models.CharField(blank=True, help_text='例如：产品经理、前端工程师', max_length=50, null=True, verbose_name='当前职位')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
                'db_table': 'user_basic_info',
            },
        ),
    ]
