# Generated by Django 4.2.17 on 2024-12-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '语言能力', 'verbose_name_plural': '语言能力'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '作品集', 'verbose_name_plural': '作品集'},
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='position',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='salary_min',
        ),
        migrations.RemoveField(
            model_name='jobintention',
            name='salary_type',
        ),
        migrations.RemoveField(
            model_name='language',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='language',
            name='score',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profilelayout',
            name='sections',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='jobintention',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='jobintention',
            name='expected_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='期望城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobintention',
            name='expected_salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='期望薪资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobintention',
            name='job_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='求职状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolios/', verbose_name='作品图片'),
        ),
        migrations.AddField(
            model_name='profilelayout',
            name='layout',
            field=models.JSONField(default=dict, verbose_name='布局配置'),
        ),
        migrations.AddField(
            model_name='project',
            name='achievement',
            field=models.TextField(blank=True, verbose_name='项目成果'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='avatar',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='avatars/', verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='location',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='所在地'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jobintention',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='求职说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobintention',
            name='job_type',
            field=models.CharField(max_length=50, verbose_name='工作类型'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, verbose_name='语言描述'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(max_length=50, verbose_name='掌握程度'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='profilelayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterModelTable(
            name='jobintention',
            table=None,
        ),
    ]
