# Generated by Django 4.2.17 on 2024-12-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="description",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="is_internship",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="achievements",
            field=models.TextField(blank=True, verbose_name="工作成果"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="company_description",
            field=models.TextField(blank=True, verbose_name="公司描述"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="department",
            field=models.CharField(blank=True, max_length=100, verbose_name="部门"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="responsibilities",
            field=models.TextField(blank=True, verbose_name="工作职责"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="是否当前工作"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(verbose_name="开始时间"),
        ),
    ]
