# Generated by Django 4.2.17 on 2025-01-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="学习项目")),
                (
                    "institution",
                    models.CharField(max_length=100, verbose_name="培训机构"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否在学"),
                ),
                ("description", models.TextField(blank=True, verbose_name="学习描述")),
                (
                    "certificate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="证书编号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习经历",
                "verbose_name_plural": "学习经历",
                "ordering": ["-start_date"],
            },
        ),
    ]
