# Generated by Django 4.2.7 on 2024-12-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_basicinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
