# Generated by Django 4.2.17 on 2024-12-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_workexperience_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="highlights",
            field=models.TextField(blank=True, verbose_name="项目亮点"),
        ),
        migrations.AddField(
            model_name="skill",
            name="projects",
            field=models.TextField(blank=True, verbose_name="相关项目"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="technologies",
            field=models.TextField(blank=True, verbose_name="技术栈"),
        ),
    ]
