# Generated by Django 4.2.17 on 2025-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_uid_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(
                blank=True,
                help_text="系统生成的唯一标识符",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="用户ID",
            ),
        ),
    ]
