# Generated by Django 4.2.17 on 2024-12-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_basicinfo_bio_remove_basicinfo_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
