# Generated by Django 4.2.17 on 2024-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_portfolio_highlights_skill_projects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinfo",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="所在地"),
        ),
    ]
