# Generated by Django 4.2.17 on 2024-12-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workexperience_is_internship_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('professional', '专业证书'), ('award', '获奖证书'), ('language', '语言证书'), ('other', '其他证书')], default='professional', max_length=20, verbose_name='证书类型'),
        ),
    ]
