# Generated by Django 4.2.17 on 2024-12-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_basicinfo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobintention",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="jobintention",
            name="description",
        ),
        migrations.RemoveField(
            model_name="jobintention",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="jobintention",
            name="industries",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="期望行业",
            ),
        ),
        migrations.AlterField(
            model_name="jobintention",
            name="job_status",
            field=models.CharField(
                choices=[("open", "在找工作"), ("closed", "暂不找工作")],
                max_length=20,
                verbose_name="求职状态",
            ),
        ),
        migrations.AlterField(
            model_name="jobintention",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "全职"),
                    ("part_time", "兼职"),
                    ("internship", "实习"),
                    ("freelance", "自由职业"),
                ],
                max_length=20,
                verbose_name="工作类型",
            ),
        ),
        migrations.AlterField(
            model_name="jobintention",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_intention",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="jobintention",
            table="users_jobintention",
        ),
    ]
