# Generated by Django 4.2.17 on 2025-01-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="用户头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="backgrounds/", verbose_name="背景图"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="个人简介"),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="职位"
            ),
        ),
    ]
