# Generated by Django 4.2.7 on 2025-01-01 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作品展示",
                "verbose_name_plural": "作品展示",
            },
        ),
        migrations.AlterModelOptions(
            name="profilelayout",
            options={},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["-proficiency", "-created_at"],
                "verbose_name": "技能特长",
                "verbose_name_plural": "技能特长",
            },
        ),
        migrations.AlterUniqueTogether(
            name="profilelayout",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="highlights",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="image",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="title",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="type",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="url",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="description",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="projects",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="link",
            field=models.URLField(blank=True, max_length=255, verbose_name="作品链接"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                default="未命名作品", max_length=100, verbose_name="作品名称"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="quality_score",
            field=models.IntegerField(default=0, verbose_name="质量分数"),
        ),
        migrations.AddField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                choices=[(1, "入门"), (2, "熟练"), (3, "精通")],
                default=1,
                verbose_name="熟练程度",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, verbose_name="技能名称"),
        ),
    ]
