# Generated by Django 4.2.7 on 2025-01-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_portfolio_options_alter_profilelayout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('weibo', '新浪微博'), ('zhihu', '知乎'), ('zcool', '站酷'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('website', '个人网站'), ('other', '其他')], max_length=50, verbose_name='平台名称'),
        ),
    ]
