# Generated by Django 4.2.17 on 2024-12-25 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_jobintention_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilelayout",
            name="ability_dimension",
            field=models.IntegerField(default=0, verbose_name="能力维度分数"),
        ),
        migrations.AddField(
            model_name="profilelayout",
            name="achievement_dimension",
            field=models.IntegerField(default=0, verbose_name="成就维度分数"),
        ),
        migrations.AddField(
            model_name="profilelayout",
            name="basic_dimension",
            field=models.IntegerField(default=0, verbose_name="基础维度分数"),
        ),
        migrations.AddField(
            model_name="profilelayout",
            name="experience_dimension",
            field=models.IntegerField(default=0, verbose_name="经验维度分数"),
        ),
        migrations.CreateModel(
            name="ProfileScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_dimension",
                    models.IntegerField(default=0, verbose_name="基础维度分数"),
                ),
                (
                    "experience_dimension",
                    models.IntegerField(default=0, verbose_name="经验维度分数"),
                ),
                (
                    "ability_dimension",
                    models.IntegerField(default=0, verbose_name="能力维度分数"),
                ),
                (
                    "achievement_dimension",
                    models.IntegerField(default=0, verbose_name="成就维度分数"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_score",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "档案评分",
                "verbose_name_plural": "档案评分",
                "db_table": "users_profile_score",
            },
        ),
    ]
