# Generated by Django 4.2.17 on 2024-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_basicinfo_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ["id"],
                "verbose_name": "语言能力",
                "verbose_name_plural": "语言能力",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作品集",
                "verbose_name_plural": "作品集",
            },
        ),
        migrations.AddField(
            model_name="portfolio",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "项目"),
                    ("website", "网站"),
                    ("app", "应用"),
                    ("article", "文章"),
                    ("other", "其他"),
                ],
                default="project",
                max_length=20,
                verbose_name="作品类型",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="language",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(
                choices=[
                    ("elementary", "入门"),
                    ("intermediate", "中级"),
                    ("advanced", "高级"),
                    ("proficient", "精通"),
                    ("native", "母语"),
                ],
                default="intermediate",
                max_length=20,
                verbose_name="掌握程度",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
