# Generated by Django 4.2.7 on 2025-01-01 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_sociallink_platform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作品集",
                "verbose_name_plural": "作品集",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["order"],
                "verbose_name": "技能",
                "verbose_name_plural": "技能",
            },
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="link",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="name",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="quality_score",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="highlights",
            field=models.TextField(blank=True, verbose_name="项目亮点"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="portfolios/", verbose_name="作品图片"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="标题"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "项目"),
                    ("website", "网站"),
                    ("app", "应用"),
                    ("article", "文章"),
                    ("other", "其他"),
                ],
                default="project",
                max_length=20,
                verbose_name="作品类型",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="url",
            field=models.URLField(blank=True, verbose_name="作品链接"),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, verbose_name="技能描述"),
        ),
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("初级", "初级"),
                    ("中级", "中级"),
                    ("高级", "高级"),
                    ("专家", "专家"),
                ],
                default="初级",
                max_length=20,
                null=True,
                verbose_name="熟练程度",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="skill",
            name="projects",
            field=models.TextField(blank=True, verbose_name="相关项目"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("weibo", "新浪微博"),
                    ("zhihu", "知乎"),
                    ("zcool", "站酷"),
                    ("douyin", "抖音"),
                    ("bilibili", "Bilibili"),
                    ("github", "GitHub"),
                    ("twitter", "Twitter"),
                    ("website", "个人网站"),
                    ("other", "其他"),
                ],
                max_length=50,
                verbose_name="平台名称",
            ),
        ),
    ]
