# Generated by Django 4.2.17 on 2025-01-11 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_vip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vip_expire_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="会员到期时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_type",
            field=models.CharField(
                choices=[
                    ("none", "普通用户"),
                    ("monthly", "月度会员"),
                    ("yearly", "年度会员"),
                    ("lifetime", "终身会员"),
                ],
                default="none",
                max_length=20,
                verbose_name="会员类型",
            ),
        ),
        migrations.CreateModel(
            name="VipOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=64, unique=True, verbose_name="订单号"),
                ),
                (
                    "vip_type",
                    models.CharField(
                        choices=[
                            ("monthly", "月度会员"),
                            ("yearly", "年度会员"),
                            ("lifetime", "终身会员"),
                        ],
                        max_length=20,
                        verbose_name="会员类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "会员订单",
                "verbose_name_plural": "会员订单",
                "ordering": ["-created_at"],
            },
        ),
    ]
