# Generated by Django 4.2.17 on 2024-12-26 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_modify_profile_score_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilescore",
            name="content_quality",
            field=models.FloatField(default=0, verbose_name="内容质量分数"),
        ),
        migrations.AddField(
            model_name="profilescore",
            name="optimized_fields",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="已优化字段"
            ),
        ),
        migrations.AlterField(
            model_name="profilescore",
            name="ability_dimension",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilescore",
            name="achievement_dimension",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilescore",
            name="basic_dimension",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilescore",
            name="experience_dimension",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profilescore",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_score",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Study",
        ),
    ]
