# Generated by Django 4.2.7 on 2025-01-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profilelayout_options_alter_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='background',
            field=models.ImageField(blank=True, upload_to='backgrounds/', verbose_name='背景图'),
        ),
    ]
