# Generated by Django 4.2.17 on 2025-01-22 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "模版分类",
                "verbose_name_plural": "模版分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模版名称")),
                ("description", models.TextField(blank=True, verbose_name="模版描述")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="templates/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="关键词")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "草稿"), (1, "发布"), (2, "下架")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="template_editor.category",
                        verbose_name="所属分类",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历模版",
                "verbose_name_plural": "简历模版",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Canvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="页码",
                    ),
                ),
                ("config", models.JSONField(verbose_name="画布配置")),
                ("elements", models.JSONField(verbose_name="画布元素")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canvases",
                        to="template_editor.template",
                        verbose_name="所属模版",
                    ),
                ),
            ],
            options={
                "verbose_name": "画布",
                "verbose_name_plural": "画布",
                "ordering": ["template", "page_number"],
                "unique_together": {("template", "page_number")},
            },
        ),
    ]
