# Generated by Django 4.2.17 on 2025-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="canvas_data",
            field=models.JSONField(
                default=list, help_text="存储多个画布的数据", verbose_name="画布数据"
            ),
        ),
        migrations.DeleteModel(
            name="Canvas",
        ),
    ]
