# Generated by Django 4.2.17 on 2025-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_editor", "0002_template_canvas_data_delete_canvas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="canvas_data",
        ),
        migrations.AddField(
            model_name="template",
            name="pages",
            field=models.JSONField(
                default=list,
                help_text="存储多个画布页面的数据",
                verbose_name="画布页面",
            ),
        ),
    ]
