# Generated by Django 4.2.17 on 2025-01-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_editor", "0005_template_liked_by_template_likes_template_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_recommended",
            field=models.BooleanField(
                default=False, help_text="设置为推荐模板", verbose_name="是否推荐"
            ),
        ),
    ]
