# Generated by Django 4.2.7 on 2025-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=64, unique=True, verbose_name="订单号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("days", models.IntegerField(verbose_name="天数")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("alipay", "支付宝"), ("wechat", "微信支付")],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "paid_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                (
                    "tier_type",
                    models.CharField(
                        choices=[("free", "免费用户"), ("premium", "付费会员")],
                        max_length=20,
                        verbose_name="等级类型",
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="月付价格"
                    ),
                ),
                (
                    "price_quarterly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="季付价格"
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="年付价格"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认等级"),
                ),
                ("description", models.TextField(blank=True, verbose_name="等级描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会员等级",
                "verbose_name_plural": "会员等级",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PointRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="积分变动")),
                ("balance", models.IntegerField(verbose_name="变动后余额")),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="事件类型"),
                ),
                ("description", models.CharField(max_length=200, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "event_type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="事件类型"
                    ),
                ),
                ("points", models.IntegerField(verbose_name="积分值")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "积分规则",
                "verbose_name_plural": "积分规则",
            },
        ),
        migrations.CreateModel(
            name="Privilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="权益名称")),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="权益标识"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="权益描述")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("boolean", "是否类型"),
                            ("number", "数值类型"),
                            ("text", "文本类型"),
                        ],
                        max_length=20,
                        verbose_name="值类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "权益项目",
                "verbose_name_plural": "权益项目",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TierPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(verbose_name="权益值")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "等级权益",
                "verbose_name_plural": "等级权益",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(null=True, verbose_name="到期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户会员",
                "verbose_name_plural": "用户会员",
            },
        ),
        migrations.CreateModel(
            name="UserPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="积分余额")),
                (
                    "total_earned",
                    models.IntegerField(default=0, verbose_name="总获得积分"),
                ),
                (
                    "total_spent",
                    models.IntegerField(default=0, verbose_name="总消费积分"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户积分",
                "verbose_name_plural": "用户积分",
            },
        ),
    ]
