# Generated by Django 4.2.7 on 2025-01-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpoint",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="membership.membershiptier",
                verbose_name="会员等级",
            ),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tierprivilege",
            name="privilege",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="membership.privilege"
            ),
        ),
        migrations.AddField(
            model_name="tierprivilege",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privileges",
                to="membership.membershiptier",
            ),
        ),
        migrations.AddField(
            model_name="pointrecord",
            name="rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.pointrule",
            ),
        ),
        migrations.AddField(
            model_name="pointrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershiporder",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="membership.membershiptier",
            ),
        ),
        migrations.AddField(
            model_name="membershiporder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tierprivilege",
            unique_together={("tier", "privilege")},
        ),
    ]
