# Generated by Django 4.2.17 on 2025-01-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermembership",
            name="tier",
        ),
        migrations.AddField(
            model_name="usermembership",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("none", "普通用户"),
                    ("monthly", "月度会员"),
                    ("yearly", "年度会员"),
                    ("lifetime", "终身会员"),
                ],
                default="none",
                max_length=20,
                verbose_name="会员类型",
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="expire_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="到期时间"),
        ),
    ]
