# Generated by Django 4.2.17 on 2024-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermembership",
            name="expire_time",
            field=models.DateTimeField(null=True, verbose_name="到期时间"),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="membership.membershiptier",
            ),
        ),
    ]
