# Generated by Django 4.2.17 on 2024-12-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_alter_usermembership_expire_time_and_more"),
        ("membership", "XXXX_update_user_membership_tier"),
    ]

    operations = []
