# Generated by Django 4.2.17 on 2025-01-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("template_editor", "0005_template_liked_by_template_likes_template_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="简历名称")),
                ("description", models.TextField(blank=True, verbose_name="简历描述")),
                (
                    "pages",
                    models.JSONField(
                        default=list,
                        help_text="存储多个画布页面的数据",
                        verbose_name="画布页面",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "草稿"), (1, "已发布")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="template_editor.template",
                        verbose_name="使用的模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历",
                "verbose_name_plural": "简历",
                "ordering": ["-updated_at"],
            },
        ),
    ]
