# Generated by Django 4.2.17 on 2025-01-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类编码"
                    ),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="分类图标")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "组件分类",
                "verbose_name_plural": "组件分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="分类图标"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="resume.templatecategory",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板分类",
                "verbose_name_plural": "模板分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="resume_templates/", verbose_name="缩略图"
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="是否VIP模板"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "components",
                    models.JSONField(
                        help_text='\n    [\n        {\n            "id": "组件ID",\n            "type": "组件类型",\n            "config": {\n                "fields": {  # 组件字段值\n                    "field1": "value1",\n                    "field2": "value2"\n                },\n                "styles": {  # 组件样式\n                    "width": "100%",\n                    "color": "#000"\n                },\n                "layout": {  # 布局位置\n                    "x": 0,\n                    "y": 0,\n                    "w": 12,\n                    "h": 2\n                }\n            }\n        }\n    ]\n    ',
                        verbose_name="组件配置",
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        help_text='\n    {\n        "type": "grid/flex",\n        "columns": 12,\n        "gap": "1rem",\n        "areas": [  # 布局区域定义\n            {\n                "name": "header",\n                "x": 0,\n                "y": 0,\n                "w": 12,\n                "h": 2\n            }\n        ]\n    }\n    ',
                        verbose_name="布局配置",
                    ),
                ),
                (
                    "theme",
                    models.JSONField(
                        help_text='\n    {\n        "colors": {\n            "primary": "#000000",\n            "secondary": "#666666",\n            "background": "#ffffff",\n            "accent": "#ff0000"\n        },\n        "typography": {\n            "title": {\n                "font": "Arial",\n                "size": "24px",\n                "weight": "bold"\n            },\n            "body": {\n                "font": "Arial",\n                "size": "14px",\n                "weight": "normal"\n            }\n        },\n        "spacing": {\n            "unit": "1rem",\n            "section": "2rem"\n        }\n    }\n    ',
                        verbose_name="主题配置",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="用逗号分隔的标签",
                        max_length=200,
                        verbose_name="标签",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="浏览次数"),
                ),
                ("used_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="resume.templatecategory",
                        verbose_name="模板分类",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历模板",
                "verbose_name_plural": "简历模板",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="简历名称")),
                ("content", models.JSONField(verbose_name="简历内容")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resume.resumetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历",
                "verbose_name_plural": "简历",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="组件名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("list", "列表"),
                            ("table", "表格"),
                            ("timeline", "时间线"),
                            ("title", "标题"),
                            ("paragraph", "段落"),
                            ("education", "教育经历"),
                            ("experience", "工作经历"),
                            ("skills", "技能列表"),
                            ("contact", "联系方式"),
                            ("projects", "项目经历"),
                            ("awards", "获奖经历"),
                            ("custom", "自定义组件"),
                        ],
                        max_length=20,
                        verbose_name="组件类型",
                    ),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="图标")),
                ("description", models.TextField(blank=True, verbose_name="组件描述")),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        upload_to="component_previews/",
                        verbose_name="预览图",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text='\n    {\n        "fields": [  # 组件包含的字段\n            {\n                "name": "字段名",\n                "type": "字段类型(text/number/date/select/etc)",\n                "label": "显示标签",\n                "required": true/false,\n                "default": "默认值",\n                "options": ["选项1", "选项2"]  # 如果type是select\n            }\n        ],\n        "styles": {  # 组件样式配置\n            "width": "宽度",\n            "margin": "外边距",\n            "padding": "内边距",\n            "font": "字体",\n            "color": "颜色",\n            "background": "背景"\n        },\n        "layout": {  # 组件布局配置\n            "grid": "网格位置",\n            "alignment": "对齐方式"\n        }\n    }\n    ',
                        verbose_name="组件配置",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="组件的HTML模板，支持变量插值",
                        verbose_name="组件模板",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(default=True, verbose_name="是否系统组件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="resume.componentcategory",
                        verbose_name="组件分类",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历组件",
                "verbose_name_plural": "简历组件",
                "ordering": ["category", "type", "id"],
            },
        ),
    ]
