# Generated by Django 4.2.17 on 2025-01-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumetemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "简历模板",
                "verbose_name_plural": "简历模板",
            },
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="components",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="layout",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="price",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="sort_order",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="used_count",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="views_count",
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="content",
            field=models.JSONField(
                default=dict,
                help_text="保存画布上的所有元素数据",
                verbose_name="模板内容",
            ),
        ),
    ]
